PSR-17 support
mezzio/mezzio pull request #75
Opened 2021-05-12 20:46 UTC by boesing

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes

### Description

This PR provides initial support for PSR-17. These changes are fully backward compatible considering the following cases:

- Allow either `callable` or `ResponseFactoryInterface` to be passed to `NotFoundHandler` and `ServerRequestErrorResponseGenerator`
- Do not fetch PSR-17 factory from container if one of the following coditions are met
  - `ResponseInterface` factory is changed within the `dependencies.factories` config
  - `ResponseInterface` has an alias
  - `ResponseInterface` has a `delegators` configuration

closes #54

2021-05-14 07:58 UTC, lcobucci approved these changes
This looks great @boesing, thanks!

2021-05-19 05:51 UTC, geerteltink approved these changes

2021-05-19 16:53 UTC, weierophinney requested changes
Love this!

Just don't like naming the factory decorating callables `ResponseFactory`, as it doesn't clearly indicate what it does.

2021-05-19 16:53 UTC, weierophinney commented on src/Response/ResponseFactory.php
> +final class ResponseFactory implements ResponseFactoryInterface
I'd argue for the name `CallableResponseFactoryDecorator` here. Seeing the name, my first inclination seeing the name was "oh my, we're duplicating what we do in Diactoros here?" ... but that's not the case. It's a decorator for a callable that can create a response.

2021-05-20 17:36 UTC, weierophinney approved these changes

2021-05-20 17:36 UTC, merged